### ISSUE TITLE
Cannot run two test cases when running on same notebook!!

### ISSUE THREAD

**Issue by kaifkhan281** [algattik/databricks_test#1]
When defining multiple test cases in test file and running them on same notebook, dbrickstest.run_notebook() does not seem to be running in the second test case,
but when running with different notebook it works fine. 

Test file is attached.
[test.txt](https://github.com/algattik/databricks_test/files/4249679/test.txt)

Test run output:
In second test case definition:
>              print(os.listdir(out_dir))
>              FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmphi_fhot2/out'

**Comment by algattik** [comment]
Fix released in module version 0.0.2. Please test and confirm.

**Comment by kaifkhan281** [comment]
Thanks for the update, however using module 0.0.2 now we can run same notebooks multiple times in same test case function, as you show in your example test case, but we still facing the same problem when runnning same notebook in different test case function like previously.

The problem is that if we use same function then the pytest shows it as 1 test case, but we want to show multiple test cases in our CI/CD build pipeline.

**Comment by kaifkhan281** [comment]
Thanks for the update but it seems its not properly fixed as when running same notebook in multiple test cases single time in each gives same error as it was previously. 
But when running same notebook two times in one test case function and then one time in second test case function  (as in your example 'multiple_runs_test.py') it ran successfully, this time pytest collected both test cases and ran successfully.

I have attached my test code for both cases,

This works:
 [working.txt](https://github.com/algattik/databricks_test/files/4255110/working.txt)

This gives same error as before:
[error.txt](https://github.com/algattik/databricks_test/files/4255113/error.txt)

**Comment by algattik** [comment]
> Thanks for the update but it seems its not properly fixed as when running same notebook in multiple test cases single time in each gives same error as it was previously.
> But when running same notebook two times in one test case function and then one time in second test case function (as in your example 'multiple_runs_test.py') it ran successfully, this time pytest collected both test cases and ran successfully.

I can reproduce this issue. Investigating further.

**Comment by kaifkhan281** [comment]
Also when running notebook single time in many test case function(5 in our case), the second one gives the error and after that all test case run successfully.
Hope it helps.
Thanks.

**Comment by algattik** [comment]
Should be fixed in 0.0.3. Please try again :) Thanks for your patience.

**Comment by kaifkhan281** [comment]
Thanks, its working now.
Closing this issue.
